use_frameworks!

target 'COCRouter_Example' do
    #pod 'COCRouter', :path => '../'

  pod 'RegExCategories', '~> 1.0'
  pod 'Masonry'

  target 'COCRouter_Tests' do
    inherit! :search_paths

  end
end
